@extends("layout")
    @section("content")
        @if(isset($user))
            <p>
                {{$user->unique_id}}
            </p>
        @else
            @dd("kurac")
        @endif
    @endsection
